In [1]:
import numpy

from ensemble import majority_vote, collect_predictions_from_dir, collect_predictions_from_dirs
from ensemble import averaging_predictions
from ensemble import weighted_averaging_predictions


In [18]:
dirs = [
    # '../grid-scores/eng-anal/',
    '../scores/',
    # '../grid-scores/std-anal/',
         
       ]
# dirs = ['../models/word2vec/041/3/',
#        '../models/word2vec/051/1/',
#       '../models/word2vec/065/1/',
#       '../models/word2vec/066/1/']
preds = collect_predictions_from_dirs(dirs,
                                    'train.scores')
print(preds.shape)

*** Processing dir: ../scores/
Processing file: ../scores/066/train.scores.preds
Processing file: ../scores/062/062_fg_train.scores
Processing file: ../scores/071/071_fg_train.scores
Processing file: ../scores/074/074_fg_train.scores
Processing file: ../scores/1024/1024_fg_train.scores
Processing file: ../scores/1002/1002_fg_train.scores
Processing file: ../scores/067/067_fg_train.scores
Processing file: ../scores/1009/train.scores
Processing file: ../scores/1004/1004_fg_train.scores
Processing file: ../scores/1017/1017_fg_train.scores
Processing file: ../scores/1011/train.scores
Processing file: ../scores/075/075_fg_train.scores
Processing file: ../scores/070/070_fg_train.scores
Processing file: ../scores/072/072_fg_train.scores
Processing file: ../scores/051/051_train.scores
Processing file: ../scores/1022/1022_fg_train.scores
Processing file: ../scores/1019/1019_fg_train.scores
Processing file: ../scores/065/train.scores.preds
Processing file: ../scores/060/060_fg_train.scores
Proce

In [11]:
from ensemble import majority_vote
hard_maj_preds = majority_vote(preds)
print(hard_maj_preds.shape)
print(hard_maj_preds)

(2500,)
[3 2 3 ..., 0 0 2]


In [12]:
from ensemble import hard_median_predictions
hard_med_preds = hard_median_predictions(preds)
print(hard_med_preds)

[2 2 3 ..., 1 2 2]


In [13]:
from ensemble import hard_ranked_averaging_predictions

hard_rank_preds = hard_ranked_averaging_predictions(preds)
print(hard_rank_preds)

[2 2 3 ..., 1 2 2]


In [14]:
from ensemble import hard_averaging_predictions

hard_avg_preds = hard_averaging_predictions(preds)
print(hard_avg_preds)

[3 2 3 ..., 0 2 2]


In [15]:
from ensemble import hard_geom_averaging_predictions

hard_geom_preds = hard_geom_averaging_predictions(preds)
print(hard_geom_preds)

[3 2 3 ..., 1 2 2]


In [16]:
from ensemble import hard_harm_averaging_predictions

hard_harm_preds = hard_harm_averaging_predictions(preds)
print(hard_harm_preds)

[3 2 3 ..., 1 2 2]


In [17]:
from dataset import load_data_frame
from dataset import get_answers

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

print(correct_answers[:35])
print(hard_avg_preds[:35])
print(hard_maj_preds[:35])
print(hard_rank_preds[:35])
print(hard_geom_preds[:35])
print(hard_harm_preds[:35])
print(hard_med_preds[:35])

#print(correct_answers.shape, hard_preds.shape, hard_maj_preds.shape)
from evaluation import compute_accuracy

train_acc_maj = compute_accuracy(correct_answers, hard_maj_preds)
train_avg_acc = compute_accuracy(correct_answers, hard_avg_preds)
train_rank_acc = compute_accuracy(correct_answers, hard_rank_preds)
train_geom_acc = compute_accuracy(correct_answers, hard_geom_preds)
train_harm_acc = compute_accuracy(correct_answers, hard_harm_preds)
train_med_acc = compute_accuracy(correct_answers, hard_med_preds)

print('maj', train_acc_maj)
print('avg', train_avg_acc)
print('rnk', train_rank_acc)
print('geo', train_geom_acc)
print('har', train_harm_acc)
print('med', train_med_acc)

# print(train_rank)

Loaded datasets with 2500 X 7 in 0.012797359988326207 secs

[2 2 3 1 1 1 0 0 3 2 3 3 0 2 1 1 2 0 1 1 2 2 2 3 0 1 3 3 1 1 1 1 1 0 0]
[3 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 2 3 1 2 2 1 3 3 1 3 2 1 3 2 1 1 0 2]
[3 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 0 3 1 0 2 1 3 3 2 3 0 1 1 2 3 1 0 2]
[2 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 0 3 2 2 2 1 3 3 2 3 1 1 1 2 1 1 0 2]
[3 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 2 3 1 2 2 1 3 3 1 3 2 1 3 2 1 1 0 2]
[3 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 2 3 1 2 2 1 3 3 1 3 2 1 3 2 1 1 0 2]
[2 2 3 3 1 1 0 0 2 0 3 3 0 3 2 1 0 0 3 1 1 2 1 3 3 1 3 1 1 1 2 3 1 0 2]
maj 0.5092
avg 0.5288
rnk 0.5228
geo 0.5296
har 0.5292
med 0.5256


In [31]:
preds_sum = preds.sum(axis=0)
print(preds_sum.shape)
print(preds_sum[0,:])

nans = []
for j in range(preds_sum.shape[1]):
    if numpy.isnan(preds_sum[0, j]):
        nans.append(j)

nans = numpy.array(nans)
print(nans)

(4, 176)
[  2032.35462128   2032.02507592             nan   2050.61030757
   2032.8838677    2032.73757021             nan   2303.06159793
   2031.67538761   2031.50519384   2032.60259684   2032.5870986
   2032.78117003   2032.58284594   2031.82141082   2032.35577797
   2028.52246981   2025.46700099   2047.03890807   2025.46700099
   2031.57238517   2047.03890807   2025.46700099   2032.40156906
   2025.46700099   2033.25373054   2033.25373054   2031.21100234
   2028.52246981   2031.21100234   2031.57238517   2032.40156906
   2031.42045548   2032.48307871   2033.74492402   2034.65333096
   2031.35455373   2032.65109699   2031.11418158   2031.00394777
   2032.17350707   2032.050418     2031.07724438   2030.97040198
   2032.35462128   2050.61030757   2032.8838677    2303.06159793
   2031.64051321   1860.89647961   2032.689357     2442.56956684
   2032.62188527 -23476.20006208   2032.62839505   2248.89684337
   2032.32870402   2161.59665913   2031.97602      1996.41313292
   2031.39762905 

In [18]:
import pandas
exp_log_frame = pandas.read_csv('../models/word2vec/exp_2015-12-01_14-02-51/exp.log', sep='\t')
print(exp_log_frame.head(5))
train_accs = exp_log_frame['train-acc'].values
train_accs = train_accs / train_accs.sum()
print(train_accs)

   id  alpha  cbow_mean  embedding_size  iter  min_count  negative_sampling  \
0   0   0.05          0             100    50          1                  0   
1   1   0.05          0             100    50          1                  0   
2   2   0.05          0             100    50          1                  0   
3   3   0.05          0             200    50          1                  0   
4   4   0.05          0             200    50          1                  0   

  pred_func preprocess_func retrieve_func  sample sim_func  skip_gram  \
0       sim               t           sum       0      cos          1   
1       neg               t           sum       0      cos          1   
2       gra               t           sum       0      cos          1   
3       sim               t           sum       0      cos          1   
4       neg               t           sum       0      cos          1   

   window_size  train-acc test-acc  
0           20     0.3804     None  
1           

In [20]:
weights = train_accs[[29, 34,1,14,13,10,17,31,18,21,0,24,5,2,7,6,32,26,12,19,4,3,30,9,27,33,11,25,16,28,22,8,35,20,23,15]]

In [61]:
from ensemble import logistic_predictions

weights = numpy.array([  2.10529017e+00,   7.08935971e-01,   2.99012278e+00,   4.73161502e-01,
   1.29016471e+00,   5.14166206e-01,  -1.18954591e+00,   2.35056025e+00,
   1.01779912e+00,   2.11037757e+00,   2.56582521e+00,   6.41080907e-01,
   7.19790185e-01,   5.12649849e+00,   3.96082419e-03,   9.68266001e-01,
   1.44929295e+00,   8.87057981e-04,   4.37427774e-01,   2.52648141e+00,
  -2.45098892e-04,   1.05500928e+00,  -1.45655638e-04,   2.84541622e-01,
   1.10018611e+00,  -1.30771824e-01,  -4.49731268e-01,  -6.10189443e-01,
  -1.72595846e-01,  -3.12473099e-01,   4.47089406e-04,   2.18298684e-02,
   1.76664880e-04,   2.79428679e-04,   1.18625933e-01])
weight_preds = logistic_predictions(preds, weights)

from evaluation import hard_preds
hard_preds = hard_preds(weight_preds)
print(hard_preds)

[3 2 3 ..., 1 2 2]


In [4]:
print(preds.shape)

(2500, 4)


In [7]:
from ensemble import averaging_predictions

# preds = numpy.nan_to_num(preds)
avg_preds = averaging_predictions(preds)

print(avg_preds.shape)
print(avg_preds[:10])

(2500, 4)
[[ 4.88929355  5.03107139  5.01414867  5.06548639]
 [ 4.55279876  4.95767172  5.53756523  4.95196429]
 [ 4.6208823   5.11829712  4.78859637  5.47222421]
 [ 5.44903286  5.02635023  4.2228449   5.30177201]
 [ 5.31673134  5.67792163  4.59129256  4.41405447]
 [ 5.08178209  4.97858307  4.88787766  5.05175718]
 [ 5.47109603  4.96081704  4.94113698  4.62694995]
 [ 6.1874556   4.82318364  4.43022396  4.55913681]
 [ 4.92578776  4.8773982   5.0742031   5.12261094]
 [ 5.23659444  5.02617626  5.04252268  4.69470663]]


In [8]:
from evaluation import hard_preds
hard_preds = hard_preds(avg_preds)
print(hard_preds)

[3 2 3 ..., 1 0 2]


In [13]:
from evaluation import create_submission
from dataset import numbers_to_letters
preds = numbers_to_letters(hard_preds)
create_submission(preds, '../submissions/1028.preds')

Loaded datasets with 8132 X 6 in 0.031178485995042138 secs



correctAnswer      id
0                C  102501
1                B  102502
2                B  102503
3                B  102504
4                A  102505
5                A  102506
6                C  102507
7                A  102508
8                B  102509
9                C  102510
10               A  102511
11               B  102512
12               D  102513
13               D  102514
14               B  102515
15               D  102516
16               B  102517
17               A  102518
18               D  102519
19               A  102520
20               B  102521
21               B  102522
22               C  102523
23               B  102524
24               B  102525
25               B  102526
26               C  102527
27               C  102528
28               B  102529
29               D  102530
...            ...     ...
8102             A  110603
8103             C  110604
8104             C  110605
8105             D  110606
8106             D  110607
8107             D  110608
8108             C  110609
8109             B  110610
8110             D  110611
8111             C  110612
8112             C  110613
8113             A  110614
8114             A  110615
8115             A  110616
8116             C  110617
8117             D  110618
8118             B  110619
8119             D  110620
8120             A  110621
8121             A  110622
8122             D  110623
8123             A  110624
8124             A  110625
8125             B  110626
8126             A  110627
8127             A  110628
8128             A  110629
8129             B  110630
8130             A  110631
8131             A  110632

[8132 rows x 2 columns]

In [29]:
# weights = numpy.array([0.39, 0.39, 0.38, 0.38, 0.16, 0.16])
preds = weighted_averaging_predictions(preds, weights)
print(preds.shape)

(8132, 4)


In [5]:
from dataset import load_data_frame
from dataset import get_answers

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

print(correct_answers[:35])
print(hard_preds[:35])
print(hard_maj_preds[:35])
print(hard_rank_preds[:35])
#print(correct_answers.shape, hard_preds.shape, hard_maj_preds.shape)
from evaluation import compute_accuracy

train_acc_maj = compute_accuracy(correct_answers, hard_maj_preds)
train_acc = compute_accuracy(correct_answers, hard_preds)
train_rank = compute_accuracy(correct_answers, hard_rank_preds)

# rint(train_acc_maj)
print(train_acc)
# print(train_rank)

Loaded datasets with 2500 X 7 in 0.015570883988402784 secs

[2 2 3 1 1 1 0 0 3 2 3 3 0 2 1 1 2 0 1 1 2 2 2 3 0 1 3 3 1 1 1 1 1 0 0]
[2 2 3 0 1 0 0 0 3 0 3 3 0 3 1 1 0 2 2 2 2 2 1 3 3 1 3 1 1 3 3 3 1 0 2]
0.5232


In [1]:
from dataset import get_questions_plus_answers_labelled
from dataset import load_data_frame

train_frame = load_data_frame('../data/training_set.tsv')

data_labelled = get_questions_plus_answers_labelled(train_frame)
print(data_labelled[:10])

Loaded datasets with 2500 X 7 in 0.012561668001580983 secs

[('When athletes begin to exercise, their heart rates and respiration rates increase.  At what level of organization does the human body coordinate these functions?', 'at the tissue level', 0), ('When athletes begin to exercise, their heart rates and respiration rates increase.  At what level of organization does the human body coordinate these functions?', 'at the organ level', 0), ('When athletes begin to exercise, their heart rates and respiration rates increase.  At what level of organization does the human body coordinate these functions?', 'at the system level', 1), ('When athletes begin to exercise, their heart rates and respiration rates increase.  At what level of organization does the human body coordinate these functions?', 'at the cellular level', 0), ('Which example describes a learned behavior in a dog?', 'smelling the air for odors', 0), ('Which example describes a learned behavior in a dog?', 'barking when dist

In [32]:
def binary_multiclass_answers(answers, n_answers):
    multi_answers = numpy.zeros((len(answers), n_answers), dtype=int)
    for i, ans in enumerate(answers):
        multi_answers[i, ans] = 1
    return multi_answers

In [39]:
corr_ans = binary_multiclass_answers(correct_answers, 4)
print(binary_multiclass_answers(correct_answers, 4))
print(correct_answers)

[[0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 ..., 
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 1]]
[2 2 3 ..., 3 1 3]


In [43]:
def get_preds_by_ans(preds, ans):
    return preds[:, ans, :]

preds_0 = get_preds_by_ans(preds, 0)
print(preds_0)

[[ 0.26984291  0.28311731  0.3318312  ...,  0.25541419  0.25545294
   0.26970789]
 [ 0.23627857  0.25815815  0.25918024 ...,  0.23708182  0.24295892
   0.24471269]
 [ 0.23039757  0.21814126  0.17082751 ...,  0.23427038  0.23661992
   0.24443285]
 ..., 
 [ 0.26414213  0.23186892  0.22134378 ...,  0.25039838  0.24497923
   0.24685077]
 [ 0.26652569  0.26753846  0.26799251 ...,  0.26089042  0.25615262
   0.2628133 ]
 [ 0.28613309  0.26545343  0.24847887 ...,  0.28930598  0.28482992
   0.27866105]]


In [40]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(fit_intercept=False)
lr.fit(preds_0, corr_ans[:, 0])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
print(lr.coef_)

[[  7.16431700e-01  -8.84726461e-01   1.07273351e+00   6.51948325e-01
    1.16975071e+00  -8.89198303e-01   6.55139598e-01  -7.31790801e-02
   -7.42182218e-01  -1.13051457e+00  -8.26590176e-01  -8.41747443e-01
    5.77912499e-01   6.26144494e-01  -7.73568534e-03  -7.51680369e-01
   -1.74149128e-03   6.33648204e-01  -8.16086357e-01  -3.60266263e-04
    9.01346068e-01  -6.79982995e-01  -7.72889522e-01  -1.10811706e+00
   -6.47385927e-01  -1.12657267e+00  -6.42083437e-01   1.07559216e+00
    9.84232913e-01   1.13577085e+00  -9.26089316e-01   4.35289879e-02
   -6.93298343e-01   6.66602776e-02  -6.86749879e-01  -6.39768726e-01]]


In [45]:
preds_0 = lr.predict(preds_0)
print(sum(preds_0))

36


In [3]:
import numpy

from ensemble import majority_vote

preds = numpy.array([[[0.15, 0.3, 0.1], [0.45, 0.1, 0.1], [0.4, 0.6, 0.8]],
                    [[0.2, 0.5, 0.1], [0.3, 0.2, 0.2], [0.5, 0.3, 0.7]],
                    [[0.4, 0.2, 0.5], [0.3, 0.3, 0.1], [0.3, 0.5, 0.4]],
                    [[0.1, 0.4, 0.1], [0.6, 0.5, 0.5], [0.3, 0.1, 0.4]]])
print(preds.shape)
maj_preds = majority_vote(preds)
print(maj_preds)

(4, 3, 3)
[2 2 0 1]


In [1]:
from ensemble import backward_greedy_ensemble_search
from ensemble import collect_predictions_from_dirs

from dataset import load_data_frame
from dataset import get_answers

from evaluation import compute_accuracy

from ensemble import majority_vote, hard_averaging_predictions

dirs = ['../scores/fg',
        '../scores/word2vec/',
        '../merge-all-grid-scores/'
       #'../models/word2vec/exp_2015-12-09_06-59-30/',
       #'../models/word2vec/exp_2015-12-09_09-32-45/',
       #'../models/word2vec/exp_2015-12-09_11-02-01/'
       ]
preds = collect_predictions_from_dirs(dirs,
                                    'train.scores')

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

best_preds, best_score, ids = backward_greedy_ensemble_search(preds,
                                    correct_answers,
                                    combine_rule=hard_averaging_predictions,
                                    metric=compute_accuracy,
                                            epsilon=0.005)

print(correct_answers[:35])
print(best_preds[:35])
print(ids)
print(best_score)

*** Processing dir: ../scores/fg
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1024/1024_fg_std_dflt_merge_only_flashcards_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1002/1002_fg_eng_dflt_merge.corpus-b_c_s_o_wtv10_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1004/1004_fg_eng_dflt_merge.corpus_all_wv10_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1017/1017_fg_eng_dflt_merge_only_flashcards_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1022/1022_fg_eng_dflt_merge_only_flashcards_top8_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1019/1019_fg_eng_dflt_merge_only_flashcards_top5_train.scores
Processing file: ../scores/fg/060-062-067-070-071-072-074-075/062/062_fg_eng_dflt_concepts+ext-studystack+openstax_train.scores
Processing file: ../scores/fg/060-062-067-070-071-072-074-075/071/071_fg_std_dflt_merge.corpus.txt (b,cp,ss

In [2]:
from ensemble import backward_greedy_ensemble_search_cv
from ensemble import collect_predictions_from_dirs

from dataset import load_data_frame
from dataset import get_answers

from evaluation import compute_accuracy

from ensemble import majority_vote, hard_averaging_predictions

dirs = ['../scores/fg',
        '../scores/word2vec/',
       # '../merge-all-grid-scores/'
       #'../models/word2vec/exp_2015-12-09_06-59-30/',
       #'../models/word2vec/exp_2015-12-09_09-32-45/',
       #'../models/word2vec/exp_2015-12-09_11-02-01/'
       ]
preds = collect_predictions_from_dirs(dirs,
                                    'train.scores')

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

cv_score, best_score = backward_greedy_ensemble_search_cv(preds,
                                    correct_answers,
                                    n_folds=10,
                                    combine_rule=hard_averaging_predictions,
                                    metric=compute_accuracy,
                                            epsilon=0.005)

# print(correct_answers[:35])
# print(best_preds[:35])
# print(ids)
# print(best_score)

*** Processing dir: ../scores/fg
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1024/1024_fg_std_dflt_merge_only_flashcards_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1002/1002_fg_eng_dflt_merge.corpus-b_c_s_o_wtv10_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1004/1004_fg_eng_dflt_merge.corpus_all_wv10_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1017/1017_fg_eng_dflt_merge_only_flashcards_top3_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1022/1022_fg_eng_dflt_merge_only_flashcards_top8_train.scores
Processing file: ../scores/fg/1002-1004-1017-1019-1022-1024/1019/1019_fg_eng_dflt_merge_only_flashcards_top5_train.scores
Processing file: ../scores/fg/060-062-067-070-071-072-074-075/062/062_fg_eng_dflt_concepts+ext-studystack+openstax_train.scores
Processing file: ../scores/fg/060-062-067-070-071-072-074-075/071/071_fg_std_dflt_merge.corpus.txt (b,cp,ss

In [9]:
from ensemble import backward_greedy_ensemble_search
from ensemble import collect_predictions_from_dirs

from dataset import load_data_frame
from dataset import get_answers

from evaluation import compute_accuracy
from evaluation import hard_abs_correlation_of_preds

from ensemble import majority_vote, hard_averaging_predictions
from ensemble import forward_metric_pred_selection

dirs = ['../scores/',
        # '../grid-scores/'
       #'../models/word2vec/exp_2015-12-09_06-59-30/',
       #'../models/word2vec/exp_2015-12-09_09-32-45/',
       #'../models/word2vec/exp_2015-12-09_11-02-01/'
       ]
preds = collect_predictions_from_dirs(dirs,
                                    'train.scores')

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

corr_ids = forward_metric_pred_selection(preds, 
                             compute_metric=hard_abs_correlation_of_preds,
                             threshold=.75)

print(corr_ids)

from dataset import load_data_frame
from dataset import get_answers

correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

from ensemble import hard_averaging_predictions
hard_avg_corr_preds = hard_averaging_predictions(preds[:, :, corr_ids])
print(hard_avg_corr_preds.shape)

print(correct_answers[:35])
print(hard_avg_corr_preds[:35])


from evaluation import compute_accuracy

train_acc = compute_accuracy(correct_answers, hard_avg_corr_preds)
print(train_acc)

*** Processing dir: ../scores/
Processing file: ../scores/066/train.scores.preds
Processing file: ../scores/062/062_fg_train.scores
Processing file: ../scores/071/071_fg_train.scores
Processing file: ../scores/074/074_fg_train.scores
Processing file: ../scores/1024/1024_fg_train.scores
Processing file: ../scores/1002/1002_fg_train.scores
Processing file: ../scores/067/067_fg_train.scores
Processing file: ../scores/1009/train.scores
Processing file: ../scores/1004/1004_fg_train.scores
Processing file: ../scores/1017/1017_fg_train.scores
Processing file: ../scores/1011/train.scores
Processing file: ../scores/075/075_fg_train.scores
Processing file: ../scores/070/070_fg_train.scores
Processing file: ../scores/072/072_fg_train.scores
Processing file: ../scores/051/051_train.scores
Processing file: ../scores/1022/1022_fg_train.scores
Processing file: ../scores/1019/1019_fg_train.scores
Processing file: ../scores/065/train.scores.preds
Processing file: ../scores/060/060_fg_train.scores
Proce

In [5]:
from evaluation import hard_preds

test_preds = collect_predictions_from_dirs(['../scores/'],
                                    'valid.scores')
print(test_preds.shape)
#
# extract just the best
best_test_preds = test_preds[:, :, ids]
hard_best_test_preds = hard_averaging_predictions(best_test_preds)
print(hard_best_test_preds)

from evaluation import create_submission
from dataset import numbers_to_letters
preds = numbers_to_letters(hard_best_test_preds)

ens_sub = create_submission(preds, '../submissions/1027.csv')

*** Processing dir: ../scores/
Processing file: ../scores/066/valid.scores.preds
Processing file: ../scores/062/062_fg_valid.scores
Processing file: ../scores/071/071_fg_valid.scores
Processing file: ../scores/074/074_fg_valid.scores
Processing file: ../scores/1024/1024_fg_valid.scores
Processing file: ../scores/1002/1002_fg_valid.scores
Processing file: ../scores/067/067_fg_valid.scores
Processing file: ../scores/1009/valid.scores
Processing file: ../scores/1004/1004_fg_valid.scores
Processing file: ../scores/1017/1017_fg_valid.scores
Processing file: ../scores/1011/valid.scores
Processing file: ../scores/075/075_fg_valid.scores
Processing file: ../scores/070/070_fg_valid.scores
Processing file: ../scores/072/072_fg_valid.scores
Processing file: ../scores/051/051_valid.scores
Processing file: ../scores/1022/1022_fg_valid.scores
Processing file: ../scores/1019/1019_fg_valid.scores
Processing file: ../scores/065/valid.scores.preds
Processing file: ../scores/060/060_fg_valid.scores
Proce

In [4]:
from ensemble import forward_greedy_ensemble_search
from ensemble import collect_predictions_from_dir

from dataset import load_data_frame
from dataset import get_answers

from evaluation import compute_accuracy

from ensemble import majority_vote, hard_averaging_predictions

preds = collect_predictions_from_dir('../models/word2vec/f/',
                                    'train.preds')


correct_answers = get_answers(load_data_frame('../data/training_set.tsv'), numeric=True)

best_preds, best_score, ids = forward_greedy_ensemble_search(preds,
                                    correct_answers,
                                    combine_rule=hard_averaging_predictions,
                                    metric=compute_accuracy,
                                                epsilon=0.003)

print(correct_answers[:35])
print(best_preds[:35])
print(ids)
print(best_score)

Processing file: ../models/word2vec/f/exp_2015-12-04_20-11-58/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_20-11-58/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-05_12-18-52/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-05_12-18-52/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_21-38-39/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_21-38-39/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_22-14-04/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_22-14-04/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-05_09-51-01/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-05_09-51-01/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_20-54-47/1/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-04_20-54-47/3/train.preds
Processing file: ../models/word2vec/f/exp_2015-12-05_09-14-11/1/train.preds
Processing f

In [20]:
import numpy

from ensemble import majority_vote, collect_predictions_from_dir, collect_predictions_from_dirs
from evaluation import hard_preds

dirs = [
    # '../grid-scores/eng-anal/',
    '../scores/',
    # '../grid-scores/std-anal/',
         
       ]
# dirs = ['../models/word2vec/041/3/',
#        '../models/word2vec/051/1/',
#       '../models/word2vec/065/1/',
#       '../models/word2vec/066/1/']
preds = collect_predictions_from_dirs(dirs,
                                    'train.scores')
print(preds.shape)
hard_preds_matrix = hard_preds(preds)
n_predictors = preds.shape[2]
#
# make them
train_accuracies = []
for i in range(n_predictors):
    train_accuracies.append(compute_accuracy(correct_answers, hard_preds_matrix[:, i]))
    
print(train_accuracies)

train_accuracies = numpy.array(train_accuracies)

*** Processing dir: ../scores/
Processing file: ../scores/066/train.scores.preds
Processing file: ../scores/062/062_fg_train.scores
Processing file: ../scores/071/071_fg_train.scores
Processing file: ../scores/074/074_fg_train.scores
Processing file: ../scores/1024/1024_fg_train.scores
Processing file: ../scores/1002/1002_fg_train.scores
Processing file: ../scores/067/067_fg_train.scores
Processing file: ../scores/1009/train.scores
Processing file: ../scores/1004/1004_fg_train.scores
Processing file: ../scores/1017/1017_fg_train.scores
Processing file: ../scores/1011/train.scores
Processing file: ../scores/075/075_fg_train.scores
Processing file: ../scores/070/070_fg_train.scores
Processing file: ../scores/072/072_fg_train.scores
Processing file: ../scores/051/051_train.scores
Processing file: ../scores/1022/1022_fg_train.scores
Processing file: ../scores/1019/1019_fg_train.scores
Processing file: ../scores/065/train.scores.preds
Processing file: ../scores/060/060_fg_train.scores
Proce

In [23]:
import scipy.stats
from ensemble import weighted_averaging_predictions, logistic_predictions

w_preds = weighted_averaging_predictions(preds, train_accuracies)
hard_w_preds = hard_preds(w_preds)

train_w_acc = compute_accuracy(correct_answers, hard_w_preds)
print(train_w_acc)

logistic_preds = logistic_predictions(preds, train_accuracies)
hard_log_preds = hard_preds(logistic_preds)

train_log_acc = compute_accuracy(correct_answers, hard_log_preds)
print(train_log_acc)

w_preds = weighted_averaging_predictions(preds, scipy.stats.rankdata(train_accuracies))
hard_w_preds = hard_preds(w_preds)

train_w_acc = compute_accuracy(correct_answers, hard_w_preds)
print(train_w_acc)

0.5276
0.5276
0.5268
